[tool.poetry]
name = "bd-python"
version = "0.1.0"
description = ""
authors = ["PS Onze"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
sqlalchemy = "^2.0.36"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
